
  <h3>Error has happened. Inside this application. Sorry about that.</h3>
<p><?php echo $this->message ?> (<?php echo $this->code ?>) </p>
<?php
if( $this->env == 'test' ) {
 if ( isset($this->info ) ) { ?>
<?php if ( 404 == $this->code ) { ?>
  <p><b>Reason:</b> <?= $this->info ?></p>
<?php } elseif (500 == $this->code) { ?>
  <p>Bad server, naughty server!<br />No donut for you!</p>
  <p><img src="<?php echo $this->baseUrl();?>/images/donut.jpg" /></p>
  <h4>Exception information:</h4>
 <p><b>Message:</b> <?php echo $this->info->getMessage() ?></p>
 <h4>Stack trace:</h4>
 <pre><?php echo $this->info->getTraceAsString() ?></pre>
<?php } ?>
<?php } ?>
<?php } ?>
